name: frostbite

services:

  client:
    build:
      context: ./client
    environment:
      API_URL: http://server:8080
    ports:
      - 3000:3000

  server:
    build:
      context: ./backend
    ports:
      - 8000:8080

