name: Build and push image

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "backend/**"

env:
  IMAGE_NAME: frostbite/backend

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout repository

      - name: Log in to registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io \
            -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:latest ./backend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:latest
