name: Build and deploy client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

env:
  AZURE_CONTAINER_REGISTRY: frostbiteacr
  RESOURCE_GROUP: frostbite-rg
  IMAGE_NAME: frostbite-client
  CONTAINER_APP: frostbite-client-ca

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push to registry
        run: |
          az acr build \
            --registry $AZURE_CONTAINER_REGISTRY \
            --image $IMAGE_NAME:latest \
            ./client

      - name: Update app with new image
        run: |
          az containerapp update \
            --name $CONTAINER_APP \
            --resource-group $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY.azurecr.io/$IMAGE_NAME:latest
